---
- name: "Disable local mysql repo"
  command: "dnf module disable mysql -y"
 
- name: "Add Percona yum repository"
  yum:
    name: https://repo.percona.com/yum/release/8Server/RPMS/noarch/percona-release-1.0-27.noarch.rpm
    state: present
  when: install_rpm_repositories|bool

# https://www.percona.com/doc/percona-server/LATEST/installation/yum_repo.html
- name: "Enable Percona repository (Percona version >= 8)"
  command: "percona-release setup ps{{ mysql_version_major }}{{ mysql_version_minor }}"
 
- name: "Install percona database server (Percona version < 8)"
  dnf:
    name: 
      - "Percona-Server-server-{{mysql_version_major}}{{mysql_version_minor}}"
      - "Percona-Server-client-{{mysql_version_major}}{{mysql_version_minor}}"
      - "Percona-Server-devel-{{mysql_version_major}}{{mysql_version_minor}}"
      - "Percona-Server-shared-{{mysql_version_major}}{{mysql_version_minor}}"
      - "Percona-Server-shared-compat-{{mysql_version_major}}{{mysql_version_minor}}"
    state: present
  when: mysql_version_major|int < 8

- name: "Install MySQL-python package"
  yum:
    name: "python3-PyMySQL"
    state: present

- name: "Adjust permissions of datadir"
  file:
    path: "{{ mysql_datadir }}"
    owner: "mysql"
    group: "mysql"
    mode: 0755
    state: "directory"
